### ISSUE TITLE
Mailgun: Only one parameters 'html' or 'template' is allowed

### ISSUE THREAD

**Issue by Loown** [nest-modules/mailer#358]
It's seems like I can't send emal based on templates with mailgun I have this error

`Error: Only one parameters 'html' or 'template' is allowed
    at IncomingMessage.<anonymous> (/home/ubuntu/Documents/RockU/api/node_modules/mailgun-js/lib/request.js:327:17)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  statusCode: 400
}`

this is the function I call:

`this.mailerService.sendMail({ 
      to,
      subject: 'Test mailer',
      template: 'forgot-password',
      context: {
        url: 'test'
      }
    })`

My configuration is fine

**Comment by otaviobps** [comment]
I'm using `nodemailer-mailgun-transport`, my config file is good, I can use `mailtrap` just fine, however I'm getting the same error when trying to send the email using mailgun

**Comment by creaux** [comment]
Is there any workaround for this?

**Comment by creaux** [comment]
Apparently https://github.com/orliesaurus/nodemailer-mailgun-transport introduced their own templates solution sometimes before even version 2.*. Since version 2.* it counts with **`templates` property as a string** which is used by mailgun itself.

Error message coming from `mailgun-js` library as mailgun supports their own template engine too. The outcome is that at the end of the chain it is sending `template` which is string and compiled `html` and of course mailgun doesn't suppose to do that.

It is required to use nodemailer-mailgun-transport@1.4.0 which has lack of this mailgun template feature and apparently somehow omit `template` property for a good sake of us.

So just install it and you are good to go.

**Comment by bashtem** [comment]
@creaux 
It worked absolutely fine. I can use both mailgun and mailtrap with the same config.
the nodemailer-mailgun-transport team needs to be aware of this and make the package flexible.
It's rigid in this aspect and it sucks.
