### ISSUE TITLE
How to preview email in the browser?

### ISSUE THREAD

**Issue by vtrphan** [nest-modules/mailer#408]
Can someone advise me how to preview email in the browser using this module? Thanks

**Comment by adrianwix** [comment]
I would tell something like. Oh just read the documentation https://nest-modules.github.io/mailer/docs/mailer#preview-email. But it's not up to date or not clear how to do it.
What are 
user: process.env.MAILDEV_INCOMING_USER,
pass: process.env.MAILDEV_INCOMING_PASS,
or which path should I visit to preview the email since going to localhost:1025 doesn't work

**Comment by LyricL-Gitster** [comment]
@leosuncin developed [the feature](https://github.com/nest-modules/mailer/pull/129). Maybe he could elaborate on what the configuration options mean and what it does?

**Comment by leosuncin** [comment]
Under the hood it uses [preview-email](https://github.com/forwardemail/preview-email), so it accepts true or an object with options

https://github.com/nest-modules/mailer/blob/680c67fd5618909b6705eb1c73bd55d6b94ac76c/lib/interfaces/mailer-options.interface.ts#L44-L62

@vtrphan if you want to open the browser after the email is sent this setting should do it:

```
{
  // transport and other settings
  preview: {
    open: true // open the browser https://github.com/forwardemail/preview-email#options
  },
}
```

@adrianwix the example shows how to use [maildev](https://github.com/maildev/maildev) as SMTP server for development purpose, for the case as is the email service accept user and password authentication
